PRAGMA FOREIGN_KEYS = ON;

DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS EMPREGADO;

CREATE TABLE PESSOA(
    NIF INTEGER PRIMARY KEY,
    NOME TEXT NOT NULL,
    IDADE INTEGER NOT NULL
);

CREATE TABLE EMPREGADO(
    NIF INTEGER PRIMARY KEY REFERENCES PESSOA(NIF) ON UPDATE CASCADE ON DELETE RESTRICT,
    SALARIO REAL NOT NULL,
    EMPRESA TEXT NOT NULL
);