PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS Marca;
CREATE TABLE Marca (
    IDMARCA INTEGER PRIMARY KEY,
    NOME TEXT UNIQUE NOT NULL
);

DROP TABLE IF EXISTS Modelo;
CREATE TABLE Modelo (
    IDMODELO INTEGER PRIMARY KEY,
    NOME TEXT UNIQUE NOT NULL,
    IDMARCA INTEGER REFERENCES Marca(IDMARCA)
);

DROP TABLE IF EXISTS CodPostal;
CREATE TABLE CodPostal (
    CODPOSTAL1 TEXT PRIMARY KEY,
    LOCALIDADE TEXT NOT NULL
);

DROP TABLE IF EXISTS Cliente;
CREATE TABLE Cliente (
    IDCLIENTE INTEGER PRIMARY KEY,
    NOME TEXT NOT NULL,
    MORADA TEXT NOT NULL,
    CODPOSTAL1 TEXT REFERENCES CodPostal(CODPOSTAL1),
    COSPOSTAL2 TEXT NOT NULL,
    TELEFONE INTEGER UNIQUE
);

DROP TABLE IF EXISTS Carro;
CREATE TABLE Carro (
    IDCARRO INTEGER PRIMARY KEY,
    MATRICULA TEXT UNIQUE,
    IDMODELO INTEGER REFERENCES Modelo(IDMODELO),
    IDCLIENTE INTEGER REFERENCES Cliente(IDCLIENTE)
);

DROP TABLE IF EXISTS Reparacao;
CREATE TABLE Reparacao (
    IDREPARACAO INTEGER PRIMARY KEY,
    DATAINICIO DATE,
    DATAFIM DATE,
    IDCLIENTE INTEGER REFERENCES Cliente(IDCLIENTE),
    IDCARRO INTEGER REFERENCES Carro(IDCARRO),
    CHECK(DATAFIM > DATAINICIO),
    CHECK(DATAFIM > 0  AND DATAINICIO > 0)
);

DROP TABLE IF EXISTS Peca;
CREATE TABLE Peca (
    IDPECA INTEGER PRIMARY KEY,
    CODIGO INTEGER UNIQUE,
    DESIGNACAO TEXT NOT NULL UNIQUE,
    CUSTOUNITARIO FLOAT NOT NULL,
    QUANTIDADE INTEGER,
    CHECK(QUANTIDADE > 0 AND CUSTOUNITARIO > 0)
);

DROP TABLE IF EXISTS ReparacaoPeca;
CREATE TABLE ReparacaoPeca (
    IDREPARACAO INTEGER REFERENCES Reparacao(IDREPARACAO),
    IDPECA INTEGER REFERENCES Peca(IDPECA),
    PRIMARY KEY(IDREPARACAO, IDPECA)
);

DROP TABLE IF EXISTS PecaModelo;
CREATE TABLE PecaModelo (
    IDPECA INTEGER REFERENCES Peca(IDPECA),
    IDMODELO INTEGER REFERENCES Modelo(IDMODELO),
    PRIMARY KEY(IDPECA, IDMODELO)
);

DROP TABLE IF EXISTS Especialidade;
CREATE TABLE Especialidade (
    IDESPECIALIDADE INTEGER PRIMARY KEY,
    NOME TEXT UNIQUE,
    CUSTOHORARIO FLOAT NOT NULL,
    CHECK(CUSTOHORARIO > 0)
);

DROP TABLE IF EXISTS Funcionario;
CREATE TABLE Funcionario (
    IDFUNCIONARIO INTEGER PRIMARY KEY,
    NOME TEXT NOT NULL,
    MORADA TEXT NOT NULL,
    CODPOSTAL1 TEXT REFERENCES CodPostal(CODPOSTAL1),
    CODPOSTAL2 TEXT,
    TELEFONE INTEGER,
    IDESPECIALIDADE INTEGER REFERENCES Especialidade(IDESPECIALIDADE)
);

DROP TABLE IF EXISTS FuncionarioReparacao;
CREATE TABLE FuncionarioReparacao (
    IDFUNCIONARIO INTEGER REFERENCES Funcionario(IDFUNCIONARIO),
    IDREPARACAO INTEGER REFERENCES Reparacao(IDREPARACAO),
    NUMHORAS INTEGER NOT NULL,
    PRIMARY KEY(IDFUNCIONARIO, IDREPARACAO),
    CHECK(NUMHORAS > 0)
);