PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS "Carro";
CREATE TABLE "Carro" (
	"IDCARRO"	INTEGER,
	"MATRICULA"	TEXT UNIQUE,
	"IDMODELO"	INTEGER,
	"IDCLIENTE"	INTEGER,
	PRIMARY KEY("IDCARRO"),
	FOREIGN KEY("IDCLIENTE") REFERENCES "Cliente"("IDCLIENTE"),
	FOREIGN KEY("IDMODELO") REFERENCES "Modelo"("IDMODELO")
);

DROP TABLE IF EXISTS "Cliente";
CREATE TABLE "Cliente" (
	"IDCLIENTE"	INTEGER,
	"NOME"	TEXT NOT NULL,
	"MORADA"	TEXT NOT NULL,
	"CODPOSTAL1"	TEXT,
	"CODPOSTAL2"	TEXT NOT NULL,
	"TELEFONE"	INTEGER UNIQUE,
	PRIMARY KEY("IDCLIENTE"),
	FOREIGN KEY("CODPOSTAL1") REFERENCES "CodPostal"("CODPOSTAL1")
);

DROP TABLE IF EXISTS "CodPostal";
CREATE TABLE "CodPostal" (
	"CODPOSTAL1"	TEXT,
	"LOCALIDADE"	TEXT NOT NULL,
	PRIMARY KEY("CODPOSTAL1")
);

DROP TABLE IF EXISTS "Especialidade";
CREATE TABLE "Especialidade" (
	"IDESPECIALIDADE"	INTEGER,
	"NOME"	TEXT UNIQUE,
	"CUSTOHORARIO"	REAL NOT NULL CHECK("CUSTOHORARIO" > 0),
	PRIMARY KEY("IDESPECIALIDADE")
);

DROP TABLE IF EXISTS "Funcionario";
CREATE TABLE "Funcionario" (
	"IDFUNCIONARIO"	INTEGER,
	"NOME"	TEXT NOT NULL,
	"MORADA"	TEXT NOT NULL,
	"CODPOSTAL1"	TEXT,
	"COSPOSTAL2"	TEXT,
	"TELEFONE"	INTEGER,
	"IDESPECIALIDADE"	INTEGER,
	FOREIGN KEY("IDESPECIALIDADE") REFERENCES "Especialidade"("IDESPECIALIDADE"),
	PRIMARY KEY("IDFUNCIONARIO"),
	FOREIGN KEY("CODPOSTAL1") REFERENCES "CodPostal"("CODPOSTAL1")
);

DROP TABLE IF EXISTS "FuncionarioReparacao";
CREATE TABLE "FuncionarioReparacao" (
	"IDFUNCIONARIO"	INTEGER,
	"IDREPARACAO"	INTEGER,
	"NUMHORAS"	INTEGER NOT NULL CHECK("NUMHORAS" > 0),
	PRIMARY KEY("IDFUNCIONARIO","IDREPARACAO"),
	FOREIGN KEY("IDFUNCIONARIO") REFERENCES "Funcionario"("IDFUNCIONARIO"),
	FOREIGN KEY("IDREPARACAO") REFERENCES "Reparacao"("IDREPARACAO")
);

DROP TABLE IF EXISTS "Marca";
CREATE TABLE "Marca" (
	"IDMARCA"	INTEGER,
	"NOME"	TEXT NOT NULL,
	PRIMARY KEY("IDMARCA")
);

DROP TABLE IF EXISTS "Modelo";
CREATE TABLE "Modelo" (
	"IDMODELO"	INTEGER,
	"NOME"	TEXT NOT NULL,
	"IDMARCA"	INTEGER,
	FOREIGN KEY("IDMARCA") REFERENCES "Marca"("IDMARCA"),
	PRIMARY KEY("IDMODELO")
);

DROP TABLE IF EXISTS "Peca";
CREATE TABLE "Peca" (
	"IDPECA"	INTEGER,
	"CODIGO"	INTEGER UNIQUE,
	"DESIGNACAO"	TEXT NOT NULL UNIQUE,
	"CUSTOUNITARIO"	REAL NOT NULL CHECK("CUSTOUNITARIO" > 0),
	"QUANTIDADE"	INTEGER CHECK("QUANTIDADE" > 0),
	PRIMARY KEY("IDPECA")
);

DROP TABLE IF EXISTS "PecaModelo";
CREATE TABLE "PecaModelo" (
	"IDPECA"	INTEGER,
	"IDMODELO"	INTEGER,
	FOREIGN KEY("IDMODELO") REFERENCES "Modelo"("IDMODELO"),
	FOREIGN KEY("IDPECA") REFERENCES "Peca"("IDPECA"),
	PRIMARY KEY("IDPECA","IDMODELO")
);

DROP TABLE IF EXISTS "Reparacao";
CREATE TABLE "Reparacao" (
	"IDREPARACAO"	INTEGER,
	"DATAFIM"	TEXT CHECK("DATAFIM" > 0 AND "DATAFIM" > "DATAINICIO"),
	"DATAINICIO"	TEXT CHECK("DATAINICIO" > 0),
	"IDCLIENTE"	INTEGER,
	"IDCARRO"	INTEGER,
	FOREIGN KEY("IDCLIENTE") REFERENCES "Cliente"("IDCLIENTE"),
	PRIMARY KEY("IDREPARACAO"),
	FOREIGN KEY("IDCARRO") REFERENCES "Carro"("IDCARRO")
);

DROP TABLE IF EXISTS "ReparacaoPeca";
CREATE TABLE "ReparacaoPeca" (
	"IDREPARACAO"	INTEGER,
	"IDPECA"	INTEGER,
	FOREIGN KEY("IDPECA") REFERENCES "Peca"("IDPECA"),
	PRIMARY KEY("IDREPARACAO","IDPECA"),
	FOREIGN KEY("IDREPARACAO") REFERENCES "Reparacao"("IDREPARACAO")
);