DROP TABLE IF EXISTS TEAM;
CREATE TABLE TEAM (
    NAME TEXT PRIMARY KEY,
    COUNTRY TEXT NOT NULL
);

DROP TABLE IF EXISTS AIRCRAFT;
CREATE TABLE AIRCRAFT (
    MODEL TEXT PRIMARY KEY,
    HORSEPOWER INTEGER,
    TOPSPEED INTEGER,
    WIDTH REAL,
    HEIGHT REAL,
    WEIGHT REAL
);

DROP TABLE IF EXISTS PILOT;
CREATE TABLE PILOT (
    NUM INTEGER PRIMARY KEY,
    FIRSTNAME TEXT NOT NULL,
    SURNAME TEXT NOT NULL,
    NATIONALITY TEXT NOT NULL, 
    BIRTHDAY DATE NOT NULL,
    TEAM TEXT REFERENCES TEAM(NAME),
    MODEL TEXT REFERENCES AIRCRAFT(MODEL)
);

DROP TABLE IF EXISTS RACE;
CREATE TABLE RACE (
    LOCATION TEXT,
    EDITION INTEGER,
    COUNTRY TEXT,
    RACE_DATE DATE UNIQUE,
    GATES INTEGER,
    ELIMINATIONS INTEGER,
    PRIMARY KEY(LOCATION, EDITION)
);

DROP TABLE IF EXISTS PARTICIPATION;
CREATE TABLE PARTICIPATION (
    PILOT TEXT REFERENCES PILOT(NAME),
    LOCATION TEXT REFERENCES RACE(LOCATION),
    EDITION TEXT REFERENCES RACE(EDITION),
    TRAININGTIME TIME,
    TRAININGPOS INTEGER,
    QUALIFICATIONTIME TIME,
    QUALIFICATIONPOS INTEGER,
    QUALIFICATIONPENALTY TIME,
    ELIMINATIONTIME TIME,
    ELIMINATIONPOS INTEGER,
    ELIMINATIONPENALTY TIME, 
    CHECK(TRAININGPOS >= 1 AND QUALIFICATIONPOS >= 1 AND ELIMINATIONPOS >= 1),
    CHECK(TRAININGTIME > 0 AND QUALIFICATIONTIME > 0 AND QUALIFICATIONPENALTY > 0),
    CHECK(ELIMINATIONTIME > 0 AND ELIMINATIONPENALTY > 0),
    PRIMARY KEY(PILOT, LOCATION, EDITION)
);

DROP TABLE IF EXISTS DUEL;
CREATE TABLE DUEL (
    PILOT1 TEXT REFERENCES PILOT(NAME),
    PILOT2 TEXT REFERENCES PILOT(NAME),
    LOCATION TEXT REFERENCES RACE(LOCATION),
    EDITION TEXT REFERENCES RACE(EDITION),
    DUELTYPE TEXT,
    TIMEPILOT1 TIME,
    TIMEPILOT2 TIME,
    PENALTYPILOT1 TIME,
    PENALYTYPILOT2 TIME,
    PRIMARY KEY(PILOT1, PILOT2, LOCATION, EDITION),
    CHECK(TIMEPILOT1 > 0 AND TIMEPILOT2 > 0)
);